客车:
  普通客车:
    Mc_base: 40560.0
    Mt_base: 3175.0
    Mw_base: 1900.0
    Jcx_base: 104300.0
    Jcy_base: 2966000.0
    Jcz_base: 2996000.0
    Jtx_base: 2040.0
    Jty_base: 2710.0
    Jtz_base: 4650.0
    Jwx_base: 1120.0
    Jwy_base: 160.0
    Jwz_base: 1120.0
    Kpx_base: 9000000.0
    Kpy_base: 4600000.0
    Kpz_base: 805000.0
    Ksx_base: 130000.0
    Ksy_base: 90000.0
    Ksz_base: 309000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 20000.0
    Csx_base: 0.0
    Csy_base: 35000.0
    Csz_base: 40000.0
    Lc: 9.0
    Lt: 1.25
    R: 0.4575
    Krx: 2500000.0
  提速客车:
    Mc_base: 29600.0
    Mt_base: 1700.0
    Mw_base: 1900.0
    Jcx_base: 58020.0
    Jcy_base: 2139000.0
    Jcz_base: 2139000.0
    Jtx_base: 1600.0
    Jty_base: 1700.0
    Jtz_base: 1700.0
    Jwx_base: 1067.0
    Jwy_base: 140.0
    Jwz_base: 1067.0
    Kpx_base: 24000000.0
    Kpy_base: 5100000.0
    Kpz_base: 873000.0
    Ksx_base: 1200000.0
    Ksy_base: 300000.0
    Ksz_base: 410000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 30000.0
    Csx_base: 0.0
    Csy_base: 25000.0
    Csz_base: 108700.0
    Lc: 9.0
    Lt: 1.2
    R: 0.4575
    Krx: 2500000.0
  高速客车:
    Mc_base: 34000.0
    Mt_base: 3000.0
    Mw_base: 1400.0
    Jcx_base: 75060.0
    Jcy_base: 2277000.0
    Jcz_base: 2086000.0
    Jtx_base: 2260.0
    Jty_base: 2710.0
    Jtz_base: 3160.0
    Jwx_base: 915.0
    Jwy_base: 140.0
    Jwz_base: 915.0
    Kpx_base: 10000000.0
    Kpy_base: 5000000.0
    Kpz_base: 550000.0
    Ksx_base: 150000.0
    Ksy_base: 150000.0
    Ksz_base: 400000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 6000.0
    Csx_base: 0.0
    Csy_base: 60000.0
    Csz_base: 80000.0
    Lc: 9.0
    Lt: 1.2
    R: 0.4575
    Krx: 2500000.0

机车:
  普通机车:
    Mc_base: 72452.0
    Mt_base: 15293.0
    Mw_base: 5827.0
    Jcx_base: 160400.0
    Jcy_base: 1710000.0
    Jcz_base: 1920000.0
    Jtx_base: 6263.7
    Jty_base: 59091.0
    Jtz_base: 39699.0
    Jwx_base: 2913.0
    Jwy_base: 408.0
    Jwz_base: 4126.0
    Kpx_base: 54550000.0
    Kpy_base: 4740000.0
    Kpz_base: 9615000.0
    Ksx_base: 522000.0
    Ksy_base: 460000.0
    Ksz_base: 2679000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 100000.0
    Csx_base: 0.0
    Csy_base: 60000.0
    Csz_base: 80000.0
    Lc: 5.642
    Lt: 2.15
    R: 0.625
  提速机车:
    Mc_base: 63400.0
    Mt_base: 20563.0
    Mw_base: 3239.0
    Jcx_base: 143500.0
    Jcy_base: 1521000.0
    Jcz_base: 1718000.0
    Jtx_base: 7370.0
    Jty_base: 73274.0
    Jtz_base: 78243.0
    Jwx_base: 2450.0
    Jwy_base: 405.0
    Jwz_base: 2450.0
    Kpx_base: 20000000.0
    Kpy_base: 5500000.0
    Kpz_base: 2150000.0
    Ksx_base: 426000.0
    Ksy_base: 426000.0
    Ksz_base: 1596000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 80000.0
    Csx_base: 0.0
    Csy_base: 90000.0
    Csz_base: 120000.0
    Lc: 5.39
    Lt: 2.15
    R: 0.625
  高速机车:
    Mc_base: 59364.2
    Mt_base: 5630.8
    Mw_base: 1843.5
    Jcx_base: 130500.0
    Jcy_base: 1723000.0
    Jcz_base: 1796000.0
    Jtx_base: 2202.0
    Jty_base: 9487.0
    Jtz_base: 11233.0
    Jwx_base: 1263.0
    Jwy_base: 219.0
    Jwz_base: 1285.0
    Kpx_base: 30800000.0
    Kpy_base: 4878000.0
    Kpz_base: 2399600.0
    Ksx_base: 315600.0
    Ksy_base: 315600.0
    Ksz_base: 885800.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 30000.0
    Csx_base: 0.0
    Csy_base: 50000.0
    Csz_base: 45000.0
    Lc: 5.73
    Lt: 1.5
    R: 0.525

货车:
  普通货车_重车:
    Mc_base: 77000.0
    Mt_base: 330.0
    MB_base: 470.0
    Mw_base: 1200.0
    Jcx_base: 100000.0
    Jcy_base: 1200000.0
    Jcz_base: 1070000.0
    J1y_base: 100.0
    J1z_base: 80.0
    JBz_base: 190.0
    Jtx_base: 0.0
    Jty_base: 0.0
    Jtz_base: 0.0
    Jwx_base: 740.0
    Jwy_base: 100.0
    Jwz_base: 740.0
    Kpx_base: 0.0
    Kpy_base: 0.0
    Kpz_base: 0.0
    Ksx_base: 4140000.0
    Ksy_base: 4140000.0
    Ksz_base: 5320000.0
    Ksz1_base: 769000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 0.0
    Csx_base: 0.0
    Csy_base: 0.0
    Csz_base: 0.0
    Lc: 4.25
    Lt: 0.875
    R: 0.42
  普通货车_空车:
    Mc_base: 14600.0
    Mt_base: 330.0
    MB_base: 470.0
    Mw_base: 1200.0
    Jcx_base: 26600.0
    Jcy_base: 266000.0
    Jcz_base: 284000.0
    J1y_base: 100.0
    J1z_base: 80.0
    JBz_base: 190.0
    Jtx_base: 0.0
    Jty_base: 0.0
    Jtz_base: 0.0
    Jwx_base: 740.0
    Jwy_base: 100.0
    Jwz_base: 740.0
    Kpx_base: 0.0
    Kpy_base: 0.0
    Kpz_base: 0.0
    Ksx_base: 4140000.0
    Ksy_base: 4140000.0
    Ksz_base: 5320000.0
    Ksz1_base: 769000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 0.0
    Csx_base: 0.0
    Csy_base: 0.0
    Csz_base: 0.0
    Lc: 4.25
    Lt: 0.875
    R: 0.42
  25吨轴重货车:
    Mc_base: 90000.0
    Mt_base: 460.0
    MB_base: 596.0
    Mw_base: 1145.0
    Jcx_base: 114800.0
    Jcy_base: 1381000.0
    Jcz_base: 1407500.0
    J1y_base: 192.0
    J1z_base: 175.0
    JBz_base: 244.0
    Jtx_base: 0.0
    Jty_base: 0.0
    Jtz_base: 0.0
    Jwx_base: 700.0
    Jwy_base: 100.0
    Jwz_base: 700.0
    Kpx_base: 3600000.0
    Kpy_base: 3600000.0
    Kpz_base: 17000000.0
    Ksx_base: 6500000.0
    Ksy_base: 6500000.0
    Ksz_base: 5900000.0
    Ksz1_base: 769000.0
    Cpx_base: 0.0
    Cpy_base: 0.0
    Cpz_base: 3000.0
    Csx_base: 0.0
    Csy_base: 0.0
    Csz_base: 3000.0
    Lc: 4.6
    Lt: 0.915
    R: 0.42
